name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        kb:
          - { toml: keyboard.toml, vial: vial.json }
          - { toml: keyboard2.toml, vial: vial.json }
    uses: HaoboGu/rmk/.github/workflows/user_build.yml@main
    with:
      keyboard_toml_path: ${{ matrix.kb.toml }}
      vial_json_path: ${{ matrix.kb.vial }}
